tets1

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -18,14 +18,24 @@ jobs:
       with:
         terraform_version: 0.15.x
 
-    - name: Format Terraform code
-      run: terraform fmt -check=true
-      id: format
-      env:
-        TF_IN_AUTOMATION: 'true'
-
-    - name: Fail pull request if Terraform code is not formatted correctly
-      if: ${{ failure() }}
+    - name: Get subdirectories
       run: |
-        echo "::error::Terraform code is not formatted correctly"
-        exit 1
+        subdirs=$(find . -type d -not -path '*/\.*')
+
+    - name: Terraform Formatting
+      run: |
+        for subdir in $subdirs
+        do
+          cd $subdir
+          terraform fmt
+          if [ $? -ne 0 ]; then
+            echo "Terraform formatting failed in $subdir"
+            exit 1
+          fi
+          cd -
+        done
+
+    - name: Report status
+      run: echo "Terraform formatting complete"
+
+      if: always()
